[package]
name = "hermitfile-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dockerfile-parser = { path = "../../../dockerfile-parser-rs" }
